services:
  app:
    build: .
    image: voxdole:latest
    container_name: voxdole-app
    restart: unless-stopped
    devices:
      - /dev/snd
      - /dev/gpiochip2
      - /dev/gpiochip0
    volumes:
      - /data/voxdole:/app/data
    environment:
      - VOXDOLE_DATA_DIR=/app/data
    command: ["--input-device-name", "C930e", "--output-device-name", "PRO","--relay-signal", "gpio",
          "--relay-qso-chip", "/dev/gpiochip2", "--relay-qso-line", "10",
          "--relay-wake-chip", "/dev/gpiochip0", "--relay-wake-line", "4"]
    stdin_open: true
    tty: true

  web:
    image: voxdole:latest
    container_name: voxdole-web
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - /data/voxdole:/app/data
    environment:
      - VOXDOLE_DATA_DIR=/app/data
    ports:
      - "8080:8080"
    entrypoint: ["python3"]
    command: ["-m", "webui.app", "--port", "8080"]
